name    'stepanstipl-openfire'
version '0.1.0'
source 'https://github.com/stepanstipl/puppet-openfire.git'
author 'Stepan Stipl'
license 'MIT License'
summary 'Simple module to install Openfire Jabber server on CentOS/RHEL'
description 'This module will install and configure Openfire'
project_page 'https://github.com/stepanstipl/puppet-openfire'

dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'puppetlabs/java', '>= 1.0.0'
